###
# VERTEX PAYLOADS
###
"""
Vertex payloads are generated by vertices and sent to other vertices.
They are encapsulated in vertex messages before they are sent. Every VertexPayload
must have a dest_vertex field.
"""
abstract VertexPayload

"""Get a payloads destination vertex"""
getdestvertex(vp::VertexPayload) = vp.dest_vertex

"""Debug message containing the source vertex. Used for testing or debugging only"""
immutable DebugPayload <: VertexPayload
    dest_vertex::VertexID
    source_vertex::VertexID
end

###
# VERTEX MESSAGES
###
"""An aggregate of VertexPayloads"""
immutable VertexMessage <: Message
    dest::ProcID
    value::Vector{VertexPayload}
end
