###
# Vertex Messages
###
"""Vertex messages are generated by vertices and sent to other vertices"""
abstract VertexMessage <: DataMessage

"""Debug message containing the source vertex. Used for testing or debugging only"""
immutable DebugVertexMessage <: VertexMessage
    dest::Int
    value::Int
end

###
# Load Messages
###
